// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acwcxkhakxfjvabdcfvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjd2N4a2hha3hmanZhYmRjZnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTE1NTYsImV4cCI6MjA3NDIyNzU1Nn0.TLT1NapKvgpSiIGKiqGsPpCAi1ooQx0UwlL7opai2WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});